config/routes.rb
KelloggCafe::Application.routes.draw do
  
  root 'home#index'
get '/about', controller:'about', action:'about'

  

  get '/home', controller: 'home', action: 'index'
  get '/home/menu', controller: 'home', action: 'menu', as:'home_menu'

  get '/orders/new', controller: 'orders', action: 'new', as: 'new_order'
  post '/orders', controller: 'orders', action: 'create', as: 'orders'

  get '/orders', controller: 'orders', action: 'index'
  get '/orders/:id', controller: 'orders', action: 'show', as: 'order'

  get '/orders/:id/edit', controller: 'orders', action: 'edit', as: 'edit_order'
  patch '/orders/:id', controller: 'orders', action: 'update'

  delete '/orders/:id', controller: 'orders', action: 'destroy'

  

  get '/menus/new', controller: 'menus', action: 'new', as: 'new_menu'
  post '/menus', controller: 'menus', action: 'create', as: 'menus'

  get '/menus', controller: 'menus', action: 'index'
  get '/menus/:id', controller: 'menus', action: 'show', as: 'menu'

  get '/menus/:id/edit', controller: 'menus', action: 'edit', as: 'edit_menu'
  patch '/menus/:id', controller: 'menus', action: 'update'

  delete '/menus/:id', controller: 'menus', action: 'destroy'

  get '/ordersummaries/new', controller: 'ordersummaries', action: 'new', as: 'new_ordersummary'
  post '/ordersummaries', controller: 'ordersummaries', action: 'create', as: 'ordersummaries'

  get '/ordersummaries', controller: 'ordersummaries', action: 'index'
  get '/ordersummaries/:id', controller: 'ordersummaries', action: 'show', as: 'ordersummary'

  get '/ordersummaries/:id/edit', controller: 'ordersummaries', action: 'edit', as: 'edit_ordersummary'
  patch '/ordersummaries/:id', controller: 'ordersummaries', action: 'update'

  delete '/ordersummaries/:id', controller: 'ordersummaries', action: 'destroy'

  
  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create', as: 'users'

  get '/users', controller: 'users', action: 'index'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  patch '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/menu.rb
class Menu < ActiveRecord::Base
	attr_accessible :item_picture
	mount_uploader :item_picture, ImageUploader
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/ordersummary.rb
class Ordersummary < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def menu
    @menu = Menu.order(:item_category).all
  end


end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def index
    @menus = Menu.order(:item_category).all
  end

  def show
    @menu = Menu.find_by(id: params[:id])
  end

  def new
  end

  def create
    @menu = Menu.new
    @menu.availability = params[:availability]
    @menu.item_name = params[:item_name]
    @menu.item_category = params[:item_category]
    @menu.item_picture = params[:item_picture]
    @menu.item_price = params[:item_price]
    @menu.item_description = params[:item_description]

    if @menu.save
      redirect_to menus_url, notice: "Menu created successfully."
    else
      render 'new'
    end
  end

  def edit
    @menu = Menu.find_by(id: params[:id])
  end

  def update
    @menu = Menu.find_by(id: params[:id])
    @menu.availability = params[:availability]
    @menu.item_name = params[:item_name]
    @menu.item_category = params[:item_category]
    @menu.item_picture = params[:item_picture]
    @menu.item_price = params[:item_price]
    @menu.item_description = params[:item_description]

    if @menu.save
      redirect_to menus_url, notice: "Menu updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @menu = Menu.find_by(id: params[:id])
    @menu.destroy

    redirect_to menus_url, notice: "Menu deleted."
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find_by(id: params[:id])
  end

  def new
  end

  def create
    @order = Order.new
    @order.item_id = params[:item_id]
    @order.userid = params[:userid]
    @order.ordersummaryid = params[:ordersummaryid]
    @order.item_name = params[:item_name]
    @order.item_picture = params[:item_picture]
    @order.item_category = params[:item_category]
    @order.item_quantity = params[:item_quantity]
    @order.item_price = params[:item_price]

    if @order.save
      redirect_to orders_url, notice: "Order created successfully."
    else
      render 'new'
    end
  end

  def edit
    @order = Order.find_by(id: params[:id])
  end

  def update
    @order = Order.find_by(id: params[:id])
    @order.item_id = params[:item_id]
    @order.userid = params[:userid]
    @order.ordersummaryid = params[:ordersummaryid]
    @order.item_name = params[:item_name]
    @order.item_picture = params[:item_picture]
    @order.item_category = params[:item_category]
    @order.item_quantity = params[:item_quantity]
    @order.item_price = params[:item_price]

    if @order.save
      redirect_to orders_url, notice: "Order updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @order = Order.find_by(id: params[:id])
    @order.destroy

    redirect_to orders_url, notice: "Order deleted."
  end
end

app/controllers/ordersummaries_controller.rb
class OrdersummariesController < ApplicationController

  def index
    @ordersummaries = Ordersummary.all
  end

  def show
    @ordersummary = Ordersummary.find_by(id: params[:id])
  end

  def new
  end

  def create
    @ordersummary = Ordersummary.new
    @ordersummary.orderdate = params[:orderdate]
    @ordersummary.billamount = params[:billamount]
    @ordersummary.orderstatus = params[:orderstatus]
    @ordersummary.user_id = params[:user_id]

    if @ordersummary.save
      redirect_to ordersummaries_url, notice: "Ordersummary created successfully."
    else
      render 'new'
    end
  end

  def edit
    @ordersummary = Ordersummary.find_by(id: params[:id])
  end

  def update
    @ordersummary = Ordersummary.find_by(id: params[:id])
    @ordersummary.orderdate = params[:orderdate]
    @ordersummary.billamount = params[:billamount]
    @ordersummary.orderstatus = params[:orderstatus]
    @ordersummary.user_id = params[:user_id]

    if @ordersummary.save
      redirect_to ordersummaries_url, notice: "Ordersummary updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @ordersummary = Ordersummary.find_by(id: params[:id])
    @ordersummary.destroy

    redirect_to ordersummaries_url, notice: "Ordersummary deleted."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def new
  end

  def create
    @user = User.new
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.picture = params[:picture]

    if @user.save
      redirect_to users_url, notice: "User created successfully."
    else
      render 'new'
    end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.picture = params[:picture]

    if @user.save
      redirect_to users_url, notice: "User updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy

    redirect_to users_url, notice: "User deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/About/about.html.erb
<body >
<h1>Kellogg Cafe App Created by Abhinav and Chetan: Page Under Construction</h1>
</body>

app/views/home/index.html.erb
<div class="page-header">
  	<h1>Welcome to Kellogg Cafe</h1>
	<ul class="nav nav-pills">
	  <li class="active"><%= link_to 'View Menu', home_menu_url, class: 'btn btn-info' %> </li>
	  <li><%= link_to 'Place Order', nil, class: 'btn btn-primary' %></li>
	  <li><%= link_to 'View Order Status', nil, class: 'btn btn-success' %></li>
	  <li><%= link_to 'Order History', nil, class: 'btn btn-info' %></li>
	</ul>
</div>

app/views/home/menu.html.erb
<div class="page-header">
    <h1>Menu Items</h1>
  <ul class="nav nav-pills">
    <li class="active"><%= link_to 'View Menu', home_menu_url, class: 'btn btn-info' %> </li>
    <li><%= link_to 'Place Order', nil, class: 'btn btn-primary' %></li>
    <li><%= link_to 'View Order Status', nil, class: 'btn btn-success' %></li>
    <li><%= link_to 'Order History', nil, class: 'btn btn-info' %></li>
  </ul>
</div>



<table class="table table-hover">
  <thead>
    <tr>
      <th>Availability</th>
      <th>Item name</th>
      <th>Item category</th>
      <th>Item picture</th>
      <th>Item price</th>
      <th>Item description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @menu.each do |menu| %>
      <tr>
        <td><%= menu.availability %></td>
        <td><%= menu.item_name %></td>
        <td><%= menu.item_category %></td>
        <td><%= image_tag menu.item_picture, width:80, class: "img-square" %></td>
        <td><%= menu.item_price %></td>
        <td><%= menu.item_description %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>KelloggCafe</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/flatly/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", home_url %></li>
        <li><%= link_to "Users", users_url %></li>
        <li><%= link_to "Orders", orders_url %></li>
        <li><%= link_to "Ordersummaries", ordersummaries_url %></li>
        <li><%= link_to "Menus", menus_url %></li>
        <li><%= link_to "About", about_url %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/menus/edit.html.erb
<div class="page-header">
  <h1>Editing Menu #<%= @menu.id %></h1>
</div>

<%= form_tag(menu_url(@menu), method: 'patch', class: 'form-horizontal', multipart: true) do %>
  <div class="form-group">
    <%= label_tag :availability, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :availability, @menu.availability, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_name, @menu.item_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_category, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_category, @menu.item_category, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_picture, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= file_field_tag :item_picture,  class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_price, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_price, @menu.item_price, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_description, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_description, @menu.item_description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Menu", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/menus/index.html.erb
<div class="page-header">
  <h1>Menu Items</h1>
</div>

<p><%= link_to 'Add a New Menu', new_menu_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Availability</th>
      <th>Item name</th>
      <th>Item category</th>
      <th>Item picture</th>
      <th>Item price</th>
      <th>Item description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.availability %></td>
        <td><%= menu.item_name %></td>
        <td><%= menu.item_category %></td>
        <td><%= image_tag menu.item_picture.to_s, width:80, class: "img-square" %></td>
        <td><%= menu.item_price %></td>
        <td><%= menu.item_description %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, menu_url(menu), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_menu_url(menu), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, menu_url(menu), method: 'delete', data: { confirm: "Do you really want to delete this menu?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/menus/new.html.erb
<div class="page-header">
  <h1>New Item</h1>
</div>

<%= form_tag(menus_url, method: 'post', class: 'form-horizontal', multipart: true)  do %>
  <div class="form-group">
    <%= label_tag :availability, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :availability, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_name, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_category, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_category, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_picture, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= file_field_tag :item_picture, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_price, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_price, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_description, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_description, nil, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Create Menu", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="page-header">
  <h1>Editing Order #<%= @order.id %></h1>
</div>

<%= form_tag(order_url(@order), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :item_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :item_id, @order.item_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :userid, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :userid, @order.userid, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :ordersummaryid, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :ordersummaryid, @order.ordersummaryid, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_name, @order.item_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_picture, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_picture, @order.item_picture, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_category, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_category, @order.item_category, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_quantity, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :item_quantity, @order.item_quantity, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :item_price, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :item_price, @order.item_price, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Order", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/orders/index.html.erb
<div class="page-header">
  <h1>Orders</h1>
</div>

<p><%= link_to 'Add a New Order', new_order_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Item</th>
      <th>Userid</th>
      <th>Ordersummaryid</th>
      <th>Item name</th>
      <th>Item picture</th>
      <th>Item category</th>
      <th>Item quantity</th>
      <th>Item price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.item_id %></td>
        <td><%= order.userid %></td>
        <td><%= order.ordersummaryid %></td>
        <td><%= order.item_name %></td>
        <td><%= order.item_picture %></td>
        <td><%= order.item_category %></td>
        <td><%= order.item_quantity %></td>
        <td><%= order.item_price %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, order_url(order), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_order_url(order), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, order_url(order), method: 'delete', data: { confirm: "Do you really want to delete this order?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ordersummaries/edit.html.erb
<div class="page-header">
  <h1>Editing Ordersummary #<%= @ordersummary.id %></h1>
</div>

<%= form_tag(ordersummary_url(@ordersummary), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :orderdate, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :orderdate, @ordersummary.orderdate, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :billamount, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :billamount, @ordersummary.billamount, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :orderstatus, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :orderstatus, @ordersummary.orderstatus, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :user_id, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= number_field_tag :user_id, @ordersummary.user_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update Ordersummary", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/ordersummaries/index.html.erb
<div class="page-header">
  <h1>Ordersummaries</h1>
</div>

<p><%= link_to 'Add a New Ordersummary', new_ordersummary_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Orderdate</th>
      <th>Billamount</th>
      <th>Orderstatus</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ordersummaries.each do |ordersummary| %>
      <tr>
        <td><%= ordersummary.orderdate %></td>
        <td><%= ordersummary.billamount %></td>
        <td><%= ordersummary.orderstatus %></td>
        <td><%= ordersummary.user_id %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, ordersummary_url(ordersummary), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_ordersummary_url(ordersummary), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, ordersummary_url(ordersummary), method: 'delete', data: { confirm: "Do you really want to delete this ordersummary?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ordersummaries/show.html.erb
<div class="page-header">
  <h1>Ordersummary #<%= @ordersummary.id %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Orderdate</dt>
  <dd><%= @ordersummary.orderdate %></dd>

  <dt>Billamount</dt>
  <dd><%= @ordersummary.billamount %></dd>

  <dt>Orderstatus</dt>
  <dd><%= @ordersummary.orderstatus %></dd>

  <dt>User</dt>
  <dd><%= @ordersummary.user_id %></dd>

</dl>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Editing User #<%= @user.id %></h1>
</div>

<%= form_tag(user_url(@user), method: 'patch', class: 'form-horizontal') do %>
  <div class="form-group">
    <%= label_tag :first_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :first_name, @user.first_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :last_name, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :last_name, @user.last_name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :email, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= email_field_tag :email, @user.email, class: 'form-control', :placeholder => "someone@example.com" %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :password, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= password_field_tag :password, @user.password, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag :picture, nil, class: 'col-md-2 control-label' %>
    <div class="col-md-6">
      <%= text_field_tag :picture, @user.picture, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-2 col-md-6">
      <%= submit_tag "Update User", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="page-header">
  <h1>Users</h1>
</div>

<p><%= link_to 'Add a New User', new_user_url, class: 'btn btn-primary' %></p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Picture</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= image_tag user.picture, width:40, class: "img-circle" %></td>
        <td><%= link_to '<i class="fa fa-search-plus"></i>'.html_safe, user_url(user), class: 'btn btn-primary' %></td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_user_url(user), class: 'btn btn-warning' %></td>
        <td><%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>